name: Trigger Supabase Edge Function

on:
  schedule:
    - cron: '*/1 * * * *' # every minute (UTC)
  workflow_dispatch:

jobs:
  call-edge-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -sSf \
               -X POST \
               -H "Authorization: Bearer $SUPABASE_FUNCTION_KEY" \
               https://tucwrxkpnorotmuqbgkn.supabase.co/functions/v1/process-transformations
        env:
          SUPABASE_FUNCTION_KEY: ${{ secrets.SUPABASE_FUNCTION_KEY }}

